from . import standart_commands
from . import authorization
from . import connect_lol
from . import update_matches
from . import update_all_users_matches
from . import did
from . import history
from . import matches
from . import show_pull_ups
from . import version
from . import set_coef
from . import my_stats
from . import add
